Add route for workshops and function to list workshops.
TasteMasters/api pull request #4
Opened 2024-04-12 12:39 UTC by FAFAzin

Criei a rota /workhops. Adicionei um controller 'list-workshops.controller' para buscar todos os workshops existentes e retornar em json para o front.

2024-04-12 12:49 UTC, goustkor commented on src/modules/Workshop/Repositories/workshop.repository.js
> +    return workshops;
Corrigir indentação do arquivo

2024-04-12 12:51 UTC, goustkor commented on src/modules/Workshop/use-case/list-workshops/list-workshops.controllers.js
> +      }
No ListAll pode retornar uma array vazia caso não encontre nenhuma workshop

2024-04-12 12:53 UTC, goustkor commented on src/modules/Workshop/use-case/list-workshops/list-workshops.controllers.js
> +      super.send(res, { data: usersJson });
Não deveria retornar workshopsJson?

2024-04-12 12:54 UTC, goustkor commented on test/Workshop/list-workshops.controller.spec.js
> +        deepEqual(result.body, {});
Aqui a resposta deve ser uma lista []

2024-04-12 12:56 UTC, goustkor requested changes
Corrigir: 
Controller
Test

Identação:
Repositorio

2024-04-12 21:51 UTC, FAFAzin commented
Alterações realizadas, pode verificar por favor?

2024-04-13 13:32 UTC, goustkor approved these changes

2024-04-13 13:32 UTC, merged